[package]
name = "kql-transpiler"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sqlparser = "0.43"
itertools.workspace = true
indexmap.workspace = true
serde.workspace = true
anyhow.workspace = true
